### ISSUE TITLE
Roadmap for community engagement and adoption of the testnet

### ISSUE THREAD

**Issue by nrutledge** [mlabs-haskell/congested-testnet#12]
- [ ] The roadmap clearly outlines a strategy for moving from a centralized, MLabs-hosted testnet, to a decentralized testnet maintained by the SPO community.
- [ ] The roadmap is made public.
- [ ] SPOs and Cardano developers have been engaged and are aware of the congested testnet.

**Comment by nrutledge** [comment]
Roadmap link: https://docs.google.com/document/d/1zvnts3VLkoQNGlWWNmjIRHb1FyYI2_fCeESk0lfLpec/edit?usp=sharing
